questions = [
    {
        'Main question': 'What is the difference between Python syntax and semantics?',
        'Explanation': 'Explain the distinction between Python syntax, which defines the structure of the language, and semantics, which determines the meaning of Python constructs.',
        'Follow-up questions': [
            'How does understanding Python syntax help in writing correct code?',
            'Can you provide an example of a syntax error in Python code?',
            'Why is it important to grasp both syntax and semantics to become proficient in Python programming?'
        ]
    },
    {
        'Main question': 'How do you define Python syntax?',
        'Explanation': 'Clarify what Python syntax encompasses and how adherence to these rules is crucial for writing valid Python code.',
        'Follow-up questions': [
            'What are some common syntax elements in Python programming?',
            'How does indentation play a role in Python syntax?',
            'Can you explain the significance of colons in Python syntax when defining functions or loops?'
        ]
    },
    {
        'Main question': 'Why is understanding Python semantics important for programmers?',
        'Explanation': 'Illustrate the significance of grasping Python semantics in order to comprehend the behavior and implications of code execution.',
        'Follow-up questions': [
            'How do Python semantics influence the runtime behavior of a program?',
            'Can you explain the difference between dynamic and static semantics in Python?',
            'In what ways does knowledge of Python semantics contribute to writing efficient and bug-free code?'
        ]
    },
    {
        'Main question': 'Can you provide an example of a Python syntax error and explain how to troubleshoot it?',
        'Explanation': 'Demonstrate a Python syntax error scenario and elucidate the steps a programmer can take to identify and rectify such errors.',
        'Follow-up questions': [
            'What tools or techniques can be used to detect syntax errors in Python code?',
            'How do error messages generated by Python help in diagnosing syntax issues?',
            'Why is practicing debugging skills important for resolving syntax errors in Python code?'
        ]
    },
    {
        'Main question': 'How do Python operators contribute to the syntax and semantics of the language?',
        'Explanation': 'Discuss the role of operators in Python syntax, including arithmetic, comparison, logical, and assignment operators, as well as their impact on program semantics.',
        'Follow-up questions': [
            'Can you explain the precedence and associativity rules of operators in Python?',
            'How do operator overloading and magic methods influence the behavior of Python objects?',
            'In what ways do different types of operators enhance the expressiveness and functionality of Python code?'
        ]
    }
]
